title: 'MAHAMDAN!'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.07060105
  brandStrength: 0.5573492
  lightness: 0.5897182
  brandColors:
    - '#FFFFFF'
    - '#211E1F'
    - '#D0CFCF'
    - '#545353'
    - '#777677'
  rhythmicContrast: 0.4142826
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: mahamdan
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.0638559
layout_spectrum: 0.06922354
