name: mahamdan
favicon: null
layout_spectrum: 0.06922354
typography_spectrum: 0.0638559
title: 'MAHAMDAN!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#211E1F'
    - '#D0CFCF'
    - '#545353'
    - '#777677'
  brandStrength: 0.5573492
  lightness: 0.5897182
  saturation: 0.07060105
  rhythmicContrast: 0.4142826
purpose: []
